// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE8OtzVLXHRH_sgjr2riEaj5oDBUTKgRk',
    appId: '1:682843229299:web:ebed7c0530bc29a5cbee06',
    messagingSenderId: '682843229299',
    projectId: 'ghar-shift-cacd8',
    authDomain: 'ghar-shift-cacd8.firebaseapp.com',
    storageBucket: 'ghar-shift-cacd8.firebasestorage.app',
    measurementId: 'G-88BXTRQKYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhb-geXGph5crjPkKtMHJ1_u2K2NVx9LA',
    appId: '1:682843229299:android:3f93f15d5968fc2ecbee06',
    messagingSenderId: '682843229299',
    projectId: 'ghar-shift-cacd8',
    storageBucket: 'ghar-shift-cacd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQaIo1IS9Vqwz7zZSmWtXARQLbMRf2cTg',
    appId: '1:682843229299:ios:9778e89a936df4f8cbee06',
    messagingSenderId: '682843229299',
    projectId: 'ghar-shift-cacd8',
    storageBucket: 'ghar-shift-cacd8.firebasestorage.app',
    iosBundleId: 'com.example.gharShift',
  );
}
